substitutions:
    _REGION: us-central1
    _REPOSITORY: coverset
    _TAG: dev

steps:
    - name: gcr.io/cloud-builders/docker
      id: build-api
      args:
          - build
          - -f
          - Dockerfile.api
          - -t
          - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/coverset-api:${_TAG}
          - .

    - name: gcr.io/cloud-builders/docker
      id: build-worker
      args:
          - build
          - -f
          - Dockerfile.worker
          - -t
          - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/coverset-worker:${_TAG}
          - .

    - name: gcr.io/cloud-builders/docker
      id: build-web
      args:
          - build
          - -f
          - apps/web/Dockerfile
          - -t
          - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/coverset-web:${_TAG}
          - .

images:
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/coverset-api:${_TAG}
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/coverset-worker:${_TAG}
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/coverset-web:${_TAG}

options:
    logging: CLOUD_LOGGING_ONLY
